---
title: "My Homepage"
---
###**R Markdown and Leaflet**
Leaflet is one of the most popular JavaScript libraries for producing interactive maps. This webpage shows different features of Leaflet Maps. 

#### Adding Many Circle Markers, Popups, and Drawing Rectangle to My Leaflet Map
```{r, echo=TRUE}
# FINAL map
library(leaflet)
library(mapview)

rice_map <- leaflet()%>%
  setView(lng=-95.403981, lat=29.716386, zoom=15)%>%
  addRectangles(
    lng1=-95.396821, lat1=29.722918,
    lng2=-95.405175, lat2=29.715,
    fillColor = "purple")%>%
  addProviderTiles(providers$Esri.NatGeoWorldMap)%>%
  addCircleMarkers(lng = -95.399, lat = 29.721, color = 'red', group = 'red', popup="Stats") %>%
  addCircleMarkers(lng = -95.4, lat = 29.719, color = 'blue', group = 'blue', popup="Library") %>%
  addCircleMarkers(lng = -95.403, lat = 29.72, color = 'green', group = 'green', popup="Chemistry") %>%
  addCircleMarkers(lng = -95.403, lat = 29.718, color = 'yellow', group = 'yellow', popup="Jonnes Business") %>%
  addCircleMarkers(lng = -95.4009, lat = 29.7202, color = 'purple', group = 'purple', popup="Maths")

rice_map
```   




####Adding Clusters  
```{r, echo=TRUE}

# Clustering
df <- data.frame(lat = runif(500, min = 29.85, max = 29.95),
                 lng = runif(500, min = -95.45, max = -95.35))
df %>% 
  leaflet() %>%
   addProviderTiles(providers$Esri.NatGeoWorldMap) %>%
  addMarkers(clusterOptions = markerClusterOptions())

```   




####Adding Legends  
```{r, echo=TRUE}
# Legends
df <- data.frame(lat = runif(100, min = 29.85, max = 29.95),
                 lng = runif(100, min = -95.45, max = -95.35),
                 col=sample(c("red", "blue", "green"), 20, replace = TRUE),
                 stringsAsFactors = FALSE)

df %>% 
  leaflet() %>%
   addProviderTiles(providers$Esri.NatGeoWorldMap) %>%
  addCircleMarkers(color = df$col) %>%
  addLegend("bottomleft", labels = LETTERS[1:3], colors = c("blue", "red", "green"))

```  



